/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //importeras i alla klasser som vi ska använda
import oru.inf.InfException; //importeras i alla klasser som vi ska använda
import java.lang.NumberFormatException;
/**
/**
 *
 * @author lisas
 */
public class LaggTillAnstalld extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form LaggTillAnstalld
     */
    public LaggTillAnstalld(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfID = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        lblAllaAnstallda = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        lblAnstallningsDatum = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblTelefonnummer = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        tfAnstallningsFornamn = new javax.swing.JTextField();
        tfAnstallningsLosenord = new javax.swing.JTextField();
        tfAnstallningsEpost = new javax.swing.JTextField();
        tfAnstallningsTelefonnummer = new javax.swing.JTextField();
        tfAnstallningsAdress = new javax.swing.JTextField();
        tfAnstallningsDatum = new javax.swing.JTextField();
        tfAnstallningsAvdelning = new javax.swing.JTextField();
        tfAnstallningsID = new javax.swing.JTextField();
        btnTillbaka1 = new javax.swing.JButton();
        btnLaggTill = new javax.swing.JButton();
        btnSlumpaLosenord = new javax.swing.JButton();
        lblNamn1 = new javax.swing.JLabel();
        tfAnstallningsEfternamn = new javax.swing.JTextField();

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAllaAnstallda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAllaAnstallda.setText("Lägg till en anställd");

        lblID.setText("ID");

        lblNamn.setText("Förnamn");

        lblAvdelning.setText("Avdelning");

        lblAnstallningsDatum.setText("Anst. datum");

        lblAdress.setText("Adress");

        lblTelefonnummer.setText("Tel.nr");

        lblEpost.setText("Epost");

        lblLosenord.setText("Lösenord");

        btnTillbaka1.setText("Tillbaka");
        btnTillbaka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbaka1ActionPerformed(evt);
            }
        });

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        btnSlumpaLosenord.setText("OBS slumpa losen???!!!");
        btnSlumpaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlumpaLosenordActionPerformed(evt);
            }
        });

        lblNamn1.setText("Efternamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAllaAnstallda)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlumpaLosenord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLaggTill)
                                .addGap(18, 18, 18)
                                .addComponent(btnTillbaka1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefonnummer)
                                    .addComponent(lblEpost)
                                    .addComponent(lblLosenord)
                                    .addComponent(lblAnstallningsDatum)
                                    .addComponent(lblAvdelning)
                                    .addComponent(lblAdress)
                                    .addComponent(lblNamn1)
                                    .addComponent(lblNamn)
                                    .addComponent(lblID))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAnstallningsID)
                                    .addComponent(tfAnstallningsFornamn)
                                    .addComponent(tfAnstallningsEfternamn)
                                    .addComponent(tfAnstallningsAdress)
                                    .addComponent(tfAnstallningsLosenord, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfAnstallningsTelefonnummer, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfAnstallningsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 6, Short.MAX_VALUE))
                                    .addComponent(tfAnstallningsAvdelning)
                                    .addComponent(tfAnstallningsEpost, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAllaAnstallda)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(tfAnstallningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfAnstallningsFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn1)
                    .addComponent(tfAnstallningsEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAnstallningsAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfAnstallningsEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonnummer)
                    .addComponent(tfAnstallningsTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnstallningsDatum)
                    .addComponent(tfAnstallningsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(tfAnstallningsLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(tfAnstallningsAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka1)
                    .addComponent(btnLaggTill)
                    .addComponent(btnSlumpaLosenord))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AllaAnstallda(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnTillbaka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbaka1ActionPerformed
// RÅKA LÄGGA TILL TVÅ GGR OCH KAN INTE TA BORT OBS
        new AllaAnstallda(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbaka1ActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        try{
           String textAID = tfAnstallningsID.getText();
           String fornamn = tfAnstallningsFornamn.getText();
           String efternamn = tfAnstallningsEfternamn.getText();
           String adress = tfAnstallningsAdress.getText();
           String epost = tfAnstallningsEpost.getText();
           String telefon = tfAnstallningsTelefonnummer.getText();
           String anstallningsDatum = tfAnstallningsDatum.getText();
           String losenord = tfAnstallningsLosenord.getText();
           String avdelningsID = tfAnstallningsFornamn.getText(); //Kolla så att det verkligen är en epost-adress!
           
           int aid = Integer.parseInt(textAID);
           int avdelning = Integer.parseInt(avdelningsID);
           
           String insertNyAnstalld = "insert into anstalld (aid, fornamn, efternamn, adress, epost, telefon, anstallningsDatum, losenord, avdelning) values "
                + "(" + aid + ",'" + fornamn + "','" + efternamn + "','" + adress + "','" + epost + "','" + telefon + "',"
                + anstallningsDatum + "," + losenord + "','" + avdelning + ");";
           idb.insert(insertNyAnstalld);
           }
        catch(InfException | NumberFormatException ex){ //Catch InfExceptions?
            System.out.println(ex);
            }
        new AllaAnstallda(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void btnSlumpaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlumpaLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSlumpaLosenordActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaggTillAnstalld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnSlumpaLosenord;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnTillbaka1;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAllaAnstallda;
    private javax.swing.JLabel lblAnstallningsDatum;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNamn1;
    private javax.swing.JLabel lblTelefonnummer;
    private javax.swing.JTextField tfAnstallningsAdress;
    private javax.swing.JTextField tfAnstallningsAvdelning;
    private javax.swing.JTextField tfAnstallningsDatum;
    private javax.swing.JTextField tfAnstallningsEfternamn;
    private javax.swing.JTextField tfAnstallningsEpost;
    private javax.swing.JTextField tfAnstallningsFornamn;
    private javax.swing.JTextField tfAnstallningsID;
    private javax.swing.JTextField tfAnstallningsLosenord;
    private javax.swing.JTextField tfAnstallningsTelefonnummer;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
}
